#!/usr/bin/python3.6


import os

basepath = '/mnt/space/Media/'

def scantree(path):
    """Recursively yield DirEntry objects for given directory."""
    for entry in os.scandir(path):
        if entry.is_dir(follow_symlinks=False):
            yield from scantree(entry.path)  # see below for Python 2.x
        else:
            yield entry

for entry in scantree(basepath):
    print(entry.path)